let db,songs=[],mediaRecorder,chunks=[],karaokeTimer;
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.menu-btn').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));scrollTo(0,0)}
$$('.menu-btn').forEach(b=>b.onclick=()=>go(b.dataset.screen));
function lesson(t,x){$('#modalTitle').textContent=t;$('#modalText').textContent='Repite cantando: '+x;$('#modal').classList.add('open');if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(x);u.lang='es-MX';u.rate=.82;u.pitch=1.2;speechSynthesis.speak(u)}}
function closeModal(){$('#modal').classList.remove('open')}
function addStars(n){let s=+(localStorage.stars||125)+n;localStorage.stars=s;updateStats()}
function updateStats(){let s=+(localStorage.stars||125);$$('[data-stars]').forEach(x=>x.textContent=s);$$('[data-level]').forEach(x=>x.textContent=Math.floor(s/50)+1)}
const req=indexedDB.open('SparklyExactV4',1);req.onupgradeneeded=e=>{db=e.target.result;if(!db.objectStoreNames.contains('songs'))db.createObjectStore('songs',{keyPath:'id',autoIncrement:true});if(!db.objectStoreNames.contains('recordings'))db.createObjectStore('recordings',{keyPath:'id',autoIncrement:true})};req.onsuccess=e=>{db=e.target.result;loadSongs();loadRecordings()};
$('#audioInput').onchange=e=>{[...e.target.files].forEach(file=>{if(file.size>50*1024*1024){alert('Máximo 50 MB');return}let tx=db.transaction('songs','readwrite');tx.objectStore('songs').add({name:file.name,blob:file,size:file.size});tx.oncomplete=loadSongs});e.target.value=''}
function loadSongs(){if(!db)return;let r=db.transaction('songs','readonly').objectStore('songs').getAll();r.onsuccess=()=>{songs=r.result;renderSongs()}}
function renderSongs(){let html='';songs.forEach((s,i)=>html+=`<div class="song"><b>🎵 ${s.name}</b><small>${(s.size/1024/1024).toFixed(1)} MB</small><button onclick="playSong(${i})">▶</button><button onclick="deleteSong(${s.id})">🗑️</button></div>`);$('#songList').innerHTML=html||'<p>Todavía no hay canciones.</p>';$('#libraryList').innerHTML=html;$('#karaokeSelect').innerHTML='<option value="">Selecciona una canción</option>'+songs.map((s,i)=>`<option value="${i}">${s.name}</option>`).join('')}
function playSong(i){let a=new Audio(URL.createObjectURL(songs[i].blob));a.play()}
function deleteSong(id){let tx=db.transaction('songs','readwrite');tx.objectStore('songs').delete(id);tx.oncomplete=loadSongs}
const lines=['Brilla, brilla, Chespita','con tu luz de corazón','canta, juega y da una vuelta','llena todo de ilusión','Sparkly llega sonriendo','y comienza la función'];
function startKaraoke(){let i=$('#karaokeSelect').value;if(i===''){alert('Selecciona una canción');return}$('#karaokePlayer').src=URL.createObjectURL(songs[+i].blob);$('#karaokePlayer').play();$('#lyrics').innerHTML=lines.map(x=>`<div>${x}</div>`).join('');let n=0;clearInterval(karaokeTimer);let ds=$$('#lyrics div');ds[0].style.color='#ffd83c';karaokeTimer=setInterval(()=>{ds.forEach(x=>x.style.color='white');n++;if(n>=ds.length){clearInterval(karaokeTimer);addStars(5);return}ds[n].style.color='#ffd83c'},2500)}
async function toggleRecord(){if(mediaRecorder&&mediaRecorder.state==='recording'){mediaRecorder.stop();$('#recordBtn').textContent='🎙️ GRABAR VOZ';return}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>chunks.push(e.data);mediaRecorder.onstop=()=>{let blob=new Blob(chunks,{type:'audio/webm'});let tx=db.transaction('recordings','readwrite');tx.objectStore('recordings').add({name:'Grabación '+new Date().toLocaleString('es-MX'),blob});tx.oncomplete=loadRecordings;stream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();$('#recordBtn').textContent='⏹️ DETENER'}catch(e){alert('Autoriza el micrófono')}}
function loadRecordings(){if(!db)return;let r=db.transaction('recordings','readonly').objectStore('recordings').getAll();r.onsuccess=()=>{$('#recordList').innerHTML=r.result.map(x=>`<div class="song"><b>${x.name}</b><button onclick="new Audio('${URL.createObjectURL(x.blob)}').play()">▶</button></div>`).join('')}}
function saveProfile(){localStorage.childName=$('#childName').value;alert('Perfil guardado')}
updateStats();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
